Resources:
  ECSInstanceLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-xxxxxxxx  # Image of ECS optimized AMI
      InstanceType: t2.medium  # Instance type
      IamInstanceProfile: !Ref ECSInstanceProfile
      SecurityGroups:
        - !Ref ECSSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config

  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PublicSubnet
      LaunchConfigurationName: !Ref ECSInstanceLaunchConfiguration
      MinSize: 1
      MaxSize: 4
      DesiredCapacity: 2
