Resources:
  MyECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 2
      LaunchType: EC2  # או FARGATE
      LoadBalancers:
        - ContainerName: my-container
          ContainerPort: 8080
          TargetGroupArn: !Ref MyTargetGroup
      TaskDefinition: !Ref MyECSTaskDefinition
