Parameters:
  Region:
    Description: "The AWS region to deploy the infrastructure"
    Type: String
    Default: "us-east-1"
    AllowedValues:
      - "us-east-1"
      - "us-west-2"
      - "eu-west-1"
      - "eu-central-1"
    ConstraintDescription: "Must be a valid AWS region."

  JenkinsInstanceType:
    Type: String
    Default: t3.medium
    Description: EC2 instance type

  Microservice1Version:
    Type: Number
    Default: 1
    Description: The version of the microservice1

  Microservice2Version:
    Type: Number
    Default: 1
    Description: The version of the microservice2
  
  Microservice1Image:
    Type: String
    Default: !Sub public.ecr.aws/v3k2f6k7/microservice1:V${Microservice1Version}
    Description: Image for microservice1

  Microservice2Image:
    Type: String
    Default: !Sub public.ecr.aws/v3k2f6k7/microservice2:V${Microservice2Version}
    Description: Image for microservice2

  PullMessageInterval:
  Type: Number
  Default: 15
  Description: Amount of seconds that the microservice 2 pull the messages from the SQS

  SmmToken:
    Type: SSecureString
    Description: The Token that we need for validate the messages. Must insert when creating the stack.
