AWSTemplateFormatVersion: '2010-09-09'
Description: "End points to the aws services for more secured approch"

Resources:
  # Gateway Endpoint - S3
  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      RouteTableIds:
        - !ImportValue PrivateRouteTableId
      VpcEndpointType: Gateway

  # Interface Endpoint - secret manager
  SecretsManagerInterfaceEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.secretsmanager"
      PrivateDnsEnabled: true
      VpcEndpointType: Interface
      SubnetIds:
        - !ImportValue PrivateSubnetId
      SecurityGroupIds:
        - !Ref EndpointSecurityGroup

  # Interface Endpoint - SQS
  SQSInterfaceEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !ImportValue VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.sqs"
      PrivateDnsEnabled: true
      VpcEndpointType: Interface
      SubnetIds:
        - !ImportValue PrivateSubnetId
      SecurityGroupIds:
        - !Ref EndpointSecurityGroup

  EndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      VpcId: !ImportValue VpcId
      GroupDescription: "Security group for VPC Endpoints"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !ImportValue PrivateSubnetCidr
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: EndpointSecurityGroup
